export const FUND_NAV_FEED_ABI = [
   {
      "inputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"target",
            "type":"address"
         }
      ],
      "name":"AddressEmptyCode",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         }
      ],
      "name":"CategoryNotSupported",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"index",
            "type":"uint256"
         }
      ],
      "name":"CategorySupported",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"implementation",
            "type":"address"
         }
      ],
      "name":"ERC1967InvalidImplementation",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ERC1967NonPayable",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"FailedCall",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidInitialization",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"NotInitializing",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"UUPSUnauthorizedCallContext",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"slot",
            "type":"bytes32"
         }
      ],
      "name":"UUPSUnsupportedProxiableUUID",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Unauthorized",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ZeroAddress",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint64",
            "name":"version",
            "type":"uint64"
         }
      ],
      "name":"Initialized",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"asset",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"nav",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"string",
            "name":"description",
            "type":"string"
         }
      ],
      "name":"NavUpdated",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"implementation",
            "type":"address"
         }
      ],
      "name":"Upgraded",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"DEFAULT_ADMIN_ROLE",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"PRICE_UPDATER_ROLE",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"UPGRADER_ROLE",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"UPGRADE_INTERFACE_VERSION",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"description",
            "type":"string"
         }
      ],
      "name":"addNavCategory",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         }
      ],
      "name":"categories",
      "outputs":[
         {
            "components":[
               {
                  "internalType":"bool",
                  "name":"isActive",
                  "type":"bool"
               },
               {
                  "internalType":"string",
                  "name":"description",
                  "type":"string"
               },
               {
                  "internalType":"uint256",
                  "name":"nav",
                  "type":"uint256"
               }
            ],
            "internalType":"struct IFundNavFeed.NavCategory[]",
            "name":"categoriesList",
            "type":"tuple[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"description",
            "type":"string"
         }
      ],
      "name":"fundNavValue",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"nav",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         }
      ],
      "name":"fundNavValue",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"totalNav",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address[]",
            "name":"assetList",
            "type":"address[]"
         }
      ],
      "name":"fundNavValue",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"navValues",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"vaultManagerAddr",
            "type":"address"
         }
      ],
      "name":"initialize",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"proxiableUUID",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"description",
            "type":"string"
         }
      ],
      "name":"removeNavCategory",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"description",
            "type":"string"
         },
         {
            "internalType":"bool",
            "name":"isActive",
            "type":"bool"
         }
      ],
      "name":"setCategoryStatus",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"asset",
            "type":"address"
         },
         {
            "internalType":"string",
            "name":"description",
            "type":"string"
         },
         {
            "internalType":"uint256",
            "name":"nav",
            "type":"uint256"
         }
      ],
      "name":"syncNavValue",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newImplementation",
            "type":"address"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"upgradeToAndCall",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"vaultManager",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   }
] as const;