export const VAULT_ASSET_ABI = [
   {
      "inputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"target",
            "type":"address"
         }
      ],
      "name":"AddressEmptyCode",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"AsyncRedeemRequired",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"implementation",
            "type":"address"
         }
      ],
      "name":"ERC1967InvalidImplementation",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ERC1967NonPayable",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"FailedCall",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"requested",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"available",
            "type":"uint256"
         }
      ],
      "name":"InsufficientClaimableAssets",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"provided",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"required",
            "type":"uint256"
         }
      ],
      "name":"InsufficientFulfillmentAmount",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"requested",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"available",
            "type":"uint256"
         }
      ],
      "name":"InsufficientShares",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidAssets",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidFundVault",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidInitialization",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidShares",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"lastNavUpdated",
            "type":"uint256"
         }
      ],
      "name":"NavStale",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"NoRequestPending",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"NotFulfilledWithdrawal",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"NotInitializing",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"Paused",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"PendingWithdrawal",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ReentrancyGuardReentrantCall",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         }
      ],
      "name":"SafeERC20FailedOperation",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"SelfSetOperator",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"UUPSUnauthorizedCallContext",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"slot",
            "type":"bytes32"
         }
      ],
      "name":"UUPSUnsupportedProxiableUUID",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Unauthorized",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         }
      ],
      "name":"UnauthorizedOperator",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ZeroAddress",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ZeroAmount",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "name":"Deposit",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint64",
            "name":"version",
            "type":"uint64"
         }
      ],
      "name":"Initialized",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"controller",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"operator",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"bool",
            "name":"approved",
            "type":"bool"
         }
      ],
      "name":"OperatorSet",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"controller",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "name":"RedeemFulfilled",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"controller",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"requestId",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "name":"RedeemRequest",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"Sweep",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"implementation",
            "type":"address"
         }
      ],
      "name":"Upgraded",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"receiver",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "name":"Withdraw",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"OPERATOR_ROLE",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"UPGRADER_ROLE",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"UPGRADE_INTERFACE_VERSION",
      "outputs":[
         {
            "internalType":"string",
            "name":"",
            "type":"string"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"asset",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"assetSurplus",
      "outputs":[
         {
            "internalType":"int256",
            "name":"",
            "type":"int256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address[]",
            "name":"controllers",
            "type":"address[]"
         }
      ],
      "name":"cancelRedeem",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"claimableRedeemRequest",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "name":"convertToAssets",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         }
      ],
      "name":"convertToShares",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"receiver",
            "type":"address"
         }
      ],
      "name":"deposit",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"totalAmount",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"controllers",
            "type":"address[]"
         }
      ],
      "name":"fulfillRedeem",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"assetTokenAddr",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"vaultManagerAddr",
            "type":"address"
         }
      ],
      "name":"initialize",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         }
      ],
      "name":"isOperator",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"maxDeposit",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"maxMint",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"maxRedeem",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"maxWithdraw",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"receiver",
            "type":"address"
         }
      ],
      "name":"mint",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         }
      ],
      "name":"operators",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"pendingRedeemRequest",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         }
      ],
      "name":"previewDeposit",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "name":"previewMint",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"previewRedeem",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"previewWithdraw",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"proxiableUUID",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"receiver",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"redeem",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"owner",
            "type":"address"
         }
      ],
      "name":"requestRedeem",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"operator",
            "type":"address"
         },
         {
            "internalType":"bool",
            "name":"approved",
            "type":"bool"
         }
      ],
      "name":"setOperator",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"share",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes4",
            "name":"interfaceId",
            "type":"bytes4"
         }
      ],
      "name":"supportsInterface",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"sweep",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"totalAssets",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newImplementation",
            "type":"address"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"upgradeToAndCall",
      "outputs":[
         
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"vaultManager",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"assets",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"receiver",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"controller",
            "type":"address"
         }
      ],
      "name":"withdraw",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"shares",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
] as const;