import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import Providers from "./providers";
import ConnectWallet from "./components/ConnectWallet";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <header className="border-b border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900">
            <nav className="mx-auto flex max-w-7xl items-center gap-6 px-4 py-3">
              <Link
                href="/"
                className="text-sm font-semibold text-neutral-900 dark:text-white"
              >
                Harmonix
              </Link>
              <Link
                href="/withdrawals"
                className="text-sm text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-white"
              >
                Withdrawals
              </Link>
              <Link
                href="/safe-transactions"
                className="text-sm text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-white"
              >
                Safe Transactions
              </Link>
              <Link
                href="/status"
                className="text-sm text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-white"
              >
                Status
              </Link>
              <Link
                href="/admin/nav"
                className="text-sm text-neutral-500 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-white"
              >
                NAV Management
              </Link>
              <div className="ml-auto">
                <ConnectWallet />
              </div>
            </nav>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
